### ISSUE TITLE
Issue on M1 macOS with current room version

### ISSUE THREAD

**Issue by Daavidaviid** [react-native-async-storage/async-storage#684]
## Current behavior

It crashes during native build time, but I was able to solve it using forcing the room version to 2.4.0-alpha03
https://stackoverflow.com/questions/68922875/room-database-is-not-working-in-mac-book-pro-m1

## Environment

- **Platforms tested**:
  - [X] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: 
- **Expo version**: 
- **Environment**:

version 1.15.8
AsyncStorage_useNextStorage=true

- **Logs/Errors that may be relevant**: 

```bash
* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

**Comment by tido64** [comment]
Resolved by #698

**Comment by samithaFHSS** [comment]
This is not yet resolved. Still getting the same error on `@react-native-async-storage/async-storage": "^1.15.13"` because room 2.3.0 does not support Apple M1 silicone.
I tried to use `AsyncStorage_next_roomVersion` to define the beta room version but it generates another error. Would appreciate if you can provide a solution for this.

Added below line to gradle.properties
```
AsyncStorage_next_roomVersion="2.4.0-beta02"
```

New error
```
Could not resolve androidx.room:room-runtime:"2.4.0-beta02".
         > Could not get resource 'https://jcenter.bintray.com/androidx/room/room-runtime/%222.4.0-beta02%22/room-runtime-%222.4.0-beta02%22.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/room/room-runtime/%222.4.0-beta02%22/room-runtime-%222.4.0-beta02%22.pom'. Received status code 400 from server: Bad Request

```
