### ISSUE TITLE
Android getItem() doesn't return anything and app becomes unresponsive (RN 0.66.1)

### ISSUE THREAD

**Issue by ricardonazario** [react-native-async-storage/async-storage#694]
### What happened?

I just upgraded to RN 0.66.1 and react-native-async-storage 1.15.9. Everything seems good on iOS but app is hanging on android whenever i call getItem.

### Version

1.15.9

### What platforms are you seeing this issue on?

- [x] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 608.50 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/ricardonazario/.rvm/rubies/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

```
async getSomething() {
    try {
           console.log('get item');
           const storageItem = await AsyncStorage.getItem('storageItem');
           console.log('GOT ITEM');
      catch (error) {
           console.log(error);
       }
}
```

If i run the above function, it logs 'get item' but then doesn't log 'GOT ITEM' or the error. Just hangs.

I tried downgrading react-native-async-storage and the issue persists.

**Comment by dilshodhamrayev** [comment]
I removed the package "react-combine-reducers" from my app and the issue was solved.

**Comment by MichDreby** [comment]
The same issue for me. During upgrading react-native to 0.68 (fabric, new architecture) I have to set up inlineRequires: true in the metro config or android build will not work. Right now AsyncStorage.getItem just hangs on.
Help needed.

**Comment by marouane-edghoughi** [comment]
@MichDreby Did you manage to solve this issue? I'm still facing it in 2023 :D

**Comment by gigby** [comment]
@marouane-edghoughi Me too :-)
How did you fix it?
