### ISSUE TITLE
Android: Could not find method getVersionOrDefault() for arguments [AsyncStorage_kotlinVersion, 1.5.31] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.

### ISSUE THREAD

**Issue by tdranv** [react-native-async-storage/async-storage#705]
### What happened?

I expected to be able to install the package and use it. Instead, the app fails to start.

### Version

1.15.10

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.98 GB / 15.81 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: 3.9.2 - C:\Python39\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Install the package.
2. run react-native link @react-native-async-storage/async-storage
3. run react-native start-android
4. An error appears:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\todor\Projects\umamai\lafayette-mobile-react\node_modules\@react-native-async-storage\async-storage\android\build.gradle' line: 40

* What went wrong:
A problem occurred evaluating project ':@react-native-async-storage_async-storage'.
> Could not find method getVersionOrDefault() for arguments [AsyncStorage_kotlinVersion, 1.5.31] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.
```

P.S. I see that this line was changed 2 hours ago: https://github.com/react-native-async-storage/async-storage/commit/fc34bfa3f712ce58c6996aaa58b77e5fec247827

**Comment by cjshearer** [comment]
same here

**Comment by tdranv** [comment]
I can confirm that `1.15.9` works correctly.

**Comment by carlosq-ordering** [comment]
I can confirm that 1.15.9 works correctly.

**Comment by Krizzu** [comment]
Hey, sorry for the issue - did not have it in our example app, when I released new version. The fix is coming up #706

**Comment by vguille** [comment]
> 
> 
> same here EDIT:
> 
> Just `npm install @react-native-async-storage/async-storage@1.15.9` for now.

Worked for me, thx :)

**Comment by Krizzu** [comment]
Fixed in v1.15.11

**Comment by Daavidaviid** [comment]
For M1 macs, 

in `android/build.gradle` : 
```
buildscript {
    …
    ext {
        …
        AsyncStorage_next_roomVersion = "2.4.0-alpha03"
    }
}
```

**Comment by maazshaikh1711** [comment]
> For M1 macs,
> 
> in `android/build.gradle` :
> 
> ```
> buildscript {
>     …
>     ext {
>         …
>         AsyncStorage_next_roomVersion = "2.4.0-alpha03"
>     }
> }
> ```

Hey Daavidaviid, I'm still getting the issue. Even after writing this line of code
